      SUBROUTINE CALLPERIOD(NN,M,IFAIL,X0,P,NPAR,TRPAR,
     *XT,Y,FM,HES,ERRY)

      EXTERNAL PRDIFX,FCN,DFDY,PERIOD
      INTEGER NN,M,NPAR
      DOUBLE PRECISION ZZ(NN),Y(NN,M),XT(M),RW(6000),
     1          USCAL(NN),FM(NN,2),IPAR(10),RH(2000),
     2          IH(100),X0(NN)
      INTEGER IFAIL,M1,NRW,NIW,NRH,NIH,ICALL(8)
      INTEGER IW(100),I,I2
      DOUBLE PRECISION P,ERRY
      DOUBLE PRECISION TRPAR(NPAR),HES(NN,NN)
      DOUBLE PRECISION RED,H,HS,TOL,T,TEND,HMAX,EPS

C
      M1=M-1

C
C  AMOUNT OF REAL- AND INTEGER-WORKSPACE
      NRW=6000
      NIW=100
C
C  SHOOTING NODES
      XT(1)=0.D0
      RED=1.D0/DBLE(M1)

      DO 10 I=2,M
10    XT(I)=XT(I-1)+RED

C
C  INITIAL VALUES OF TRAJECTORY

C
C  CALLING DIFEXP TO GENERATE INITIAL TRAJECTORY
      DO 2 I=1,NN
2     Y(I, 1) = X0(I)

      NRH=2000
      NIH=100
      IPAR(1)=0
      IPAR(2)=0
      IPAR(3)=0
      IPAR(4)=NN
      IPAR(5)=0
      IPAR(6)=0
      H=P/M1

      DO 3 I=1,NN
3     ZZ(I) = Y(I,1)

      TOL=1.D-5
      T=0

      DO 18 I=1,100
      IW(I)=0
18    CONTINUE

      DO 22 I=2,M
      TEND=XT(I)*P
      HMAX=TEND-T
      CALL PRDIFX (NN,FCN,T,ZZ,TEND,TOL,HMAX,H,HS,USCAL,NRH,RH,NIH,IH,
     2             IPAR,TRPAR)
      
      DO 4 I2=1,NN
4     Y(I2,I)=ZZ(I2) 

22    CONTINUE

C  DESIRED RELATIVE ACCURACY FOR SOLUTION
      EPS=1.D-7
C  CLASSIFICATION OF RIGHT-HAND SIDE (AUTONOMOUS SYSTEM)
      ICALL(1)=1
C  PROBLEM IS HIGHLY NONLINEAR
      ICALL(2)=2
C  MAXIMUM PERMITTED NEWTON ITERATIONS
      ICALL(3)=200
C  SOLVING VARIATIONAL EQUATION
      ICALL(4)=2
C  RANK-1 UPDATES ALLOWED
      ICALL(5)=1
C  ITERATIVE REFINEMENT IS ACTIVATED
      ICALL(6)=1
C  THE SYSTEM IS NONSTIFF
      ICALL(7)=0
C  PRINT PARAMETER
      ICALL(8)=IFAIL

      CALL PERIOD(PRDIFX,NN,M,XT,Y,P,EPS,FM,6000,RW,100,IW,
     1            ICALL,TRPAR,HES)

      ERRY=DABS(Y(1,1)-Y(1,2))+DABS(Y(1,1)-Y(1,3))
     1     +DABS(Y(1,1)-Y(1,4))+DABS(Y(1,1)-Y(1,5))

      END
