###############################################################################
#
# BVPSOL/source/Makefile
#
# revision history:
# 2011-01-18 - dka
#
###############################################################################

all: BVPSOL.mpl

clean:
	rm -f BVPSol.mpl *~*
	rm -f SubsIntoSimpleWrapper/*~
	rm -f SubsIntoSimpleWrapper/SimpleWrapperTemplate/*~ Tests/*~


BVPSOL.mpl:
	maple < BVPSol.txt