###############################################################################
#
# NPSOL/source/Makefile
#
# revision history:
# 2008-02-11 mmo
#
###############################################################################

all: NPSOL.mpl

clean:
	rm -f NPSOL.mpl *~*
	rm -f Tests/*~
	rm -f Templates/*~
	rm -f SubsIntoSimpleWrapper/*~
	rm -f SubsIntoSimpleWrapper/SimpleWrapperTemplate/*~


NPSOL.mpl:
	maple < NPSOL.txt
