###############################################################################
#
# BVPOpt/source/Makefile
#
# revision history:
# 2011-11-18 - dka
#
###############################################################################

all: BVPOpt.mpl

clean:
	rm -f BVPOpt.mpl *~*
	rm -f InternalNVVars/*~
	rm -f Templates/*~
	rm -f demo/*~


BVPOpt.mpl:
	maple < BVPOpt.txt